# Default Minimum
# Default: 1
# Must be an integer.
# 
# Default Maximum
# Default: 6
# Must be an integer and equal to or greater than the default maximum number.
# 
# Broadcast Message
# Default: -sender &3rolled (-min to -max) and got &6-result!
# Will be broadcast to the server when someone generates a random number.
# Use -sender in place of the sender of the command.
# Use -min in place of the minimum value that could have been generated.
# Use -max in place of the maximum value that could have been generated.
# Use -result in place of the random number generated.
# The message can also be formatted, for more information visit http://www.minecraftwiki.net/wiki/Formatting_codes
# The following characters can be used for formatting: 'ยง', '&'
# Using the 'ยง' character works, but leaves a strange character behind.
# I'd recommend using '&', as I have in the default message.
DefaultMinimum: 1
DefaultMaximum: 6
BroadcastMessage: -sender &3rolled (-min to -max) and got &6'-result'!